// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataPacket.proto

package cn.tomo.puppet.proto;

public final class DataPacketProto {
  private DataPacketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.tomo.puppet.proto.Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * if high bit is true,it is controller,or,it's puppet
     * </pre>
     *
     * <code>int32 sessionId = 1;</code>
     * @return The sessionId.
     */
    int getSessionId();

    /**
     * <pre>
     * type
     * </pre>
     *
     * <code>int32 messageType = 2;</code>
     * @return The messageType.
     */
    int getMessageType();

    /**
     * <pre>
     * first data segment
     * </pre>
     *
     * <code>bytes dataSegment1 = 3;</code>
     * @return The dataSegment1.
     */
    com.google.protobuf.ByteString getDataSegment1();

    /**
     * <pre>
     * second data segment for expansion in future
     * </pre>
     *
     * <code>bytes dataSegment2 = 4;</code>
     * @return The dataSegment2.
     */
    com.google.protobuf.ByteString getDataSegment2();
  }
  /**
   * Protobuf type {@code cn.tomo.puppet.proto.Packet}
   */
  public static final class Packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.tomo.puppet.proto.Packet)
      PacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Packet() {
      dataSegment1_ = com.google.protobuf.ByteString.EMPTY;
      dataSegment2_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Packet();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              sessionId_ = input.readInt32();
              break;
            }
            case 16: {

              messageType_ = input.readInt32();
              break;
            }
            case 26: {

              dataSegment1_ = input.readBytes();
              break;
            }
            case 34: {

              dataSegment2_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataPacketProto.internal_static_cn_tomo_puppet_proto_Packet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataPacketProto.internal_static_cn_tomo_puppet_proto_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DataPacketProto.Packet.class, DataPacketProto.Packet.Builder.class);
    }

    public static final int SESSIONID_FIELD_NUMBER = 1;
    private int sessionId_;
    /**
     * <pre>
     * if high bit is true,it is controller,or,it's puppet
     * </pre>
     *
     * <code>int32 sessionId = 1;</code>
     * @return The sessionId.
     */
    @java.lang.Override
    public int getSessionId() {
      return sessionId_;
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 2;
    private int messageType_;
    /**
     * <pre>
     * type
     * </pre>
     *
     * <code>int32 messageType = 2;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public int getMessageType() {
      return messageType_;
    }

    public static final int DATASEGMENT1_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString dataSegment1_;
    /**
     * <pre>
     * first data segment
     * </pre>
     *
     * <code>bytes dataSegment1 = 3;</code>
     * @return The dataSegment1.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDataSegment1() {
      return dataSegment1_;
    }

    public static final int DATASEGMENT2_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString dataSegment2_;
    /**
     * <pre>
     * second data segment for expansion in future
     * </pre>
     *
     * <code>bytes dataSegment2 = 4;</code>
     * @return The dataSegment2.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDataSegment2() {
      return dataSegment2_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sessionId_ != 0) {
        output.writeInt32(1, sessionId_);
      }
      if (messageType_ != 0) {
        output.writeInt32(2, messageType_);
      }
      if (!dataSegment1_.isEmpty()) {
        output.writeBytes(3, dataSegment1_);
      }
      if (!dataSegment2_.isEmpty()) {
        output.writeBytes(4, dataSegment2_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sessionId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sessionId_);
      }
      if (messageType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, messageType_);
      }
      if (!dataSegment1_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, dataSegment1_);
      }
      if (!dataSegment2_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, dataSegment2_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DataPacketProto.Packet)) {
        return super.equals(obj);
      }
      DataPacketProto.Packet other = (DataPacketProto.Packet) obj;

      if (getSessionId()
          != other.getSessionId()) return false;
      if (getMessageType()
          != other.getMessageType()) return false;
      if (!getDataSegment1()
          .equals(other.getDataSegment1())) return false;
      if (!getDataSegment2()
          .equals(other.getDataSegment2())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageType();
      hash = (37 * hash) + DATASEGMENT1_FIELD_NUMBER;
      hash = (53 * hash) + getDataSegment1().hashCode();
      hash = (37 * hash) + DATASEGMENT2_FIELD_NUMBER;
      hash = (53 * hash) + getDataSegment2().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DataPacketProto.Packet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataPacketProto.Packet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataPacketProto.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataPacketProto.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataPacketProto.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataPacketProto.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataPacketProto.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataPacketProto.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataPacketProto.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DataPacketProto.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataPacketProto.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataPacketProto.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DataPacketProto.Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.tomo.puppet.proto.Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.tomo.puppet.proto.Packet)
        DataPacketProto.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DataPacketProto.internal_static_cn_tomo_puppet_proto_Packet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DataPacketProto.internal_static_cn_tomo_puppet_proto_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DataPacketProto.Packet.class, DataPacketProto.Packet.Builder.class);
      }

      // Construct using DataPacketProto.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sessionId_ = 0;

        messageType_ = 0;

        dataSegment1_ = com.google.protobuf.ByteString.EMPTY;

        dataSegment2_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DataPacketProto.internal_static_cn_tomo_puppet_proto_Packet_descriptor;
      }

      @java.lang.Override
      public DataPacketProto.Packet getDefaultInstanceForType() {
        return DataPacketProto.Packet.getDefaultInstance();
      }

      @java.lang.Override
      public DataPacketProto.Packet build() {
        DataPacketProto.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public DataPacketProto.Packet buildPartial() {
        DataPacketProto.Packet result = new DataPacketProto.Packet(this);
        result.sessionId_ = sessionId_;
        result.messageType_ = messageType_;
        result.dataSegment1_ = dataSegment1_;
        result.dataSegment2_ = dataSegment2_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DataPacketProto.Packet) {
          return mergeFrom((DataPacketProto.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DataPacketProto.Packet other) {
        if (other == DataPacketProto.Packet.getDefaultInstance()) return this;
        if (other.getSessionId() != 0) {
          setSessionId(other.getSessionId());
        }
        if (other.getMessageType() != 0) {
          setMessageType(other.getMessageType());
        }
        if (other.getDataSegment1() != com.google.protobuf.ByteString.EMPTY) {
          setDataSegment1(other.getDataSegment1());
        }
        if (other.getDataSegment2() != com.google.protobuf.ByteString.EMPTY) {
          setDataSegment2(other.getDataSegment2());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DataPacketProto.Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DataPacketProto.Packet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int sessionId_ ;
      /**
       * <pre>
       * if high bit is true,it is controller,or,it's puppet
       * </pre>
       *
       * <code>int32 sessionId = 1;</code>
       * @return The sessionId.
       */
      @java.lang.Override
      public int getSessionId() {
        return sessionId_;
      }
      /**
       * <pre>
       * if high bit is true,it is controller,or,it's puppet
       * </pre>
       *
       * <code>int32 sessionId = 1;</code>
       * @param value The sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionId(int value) {
        
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * if high bit is true,it is controller,or,it's puppet
       * </pre>
       *
       * <code>int32 sessionId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSessionId() {
        
        sessionId_ = 0;
        onChanged();
        return this;
      }

      private int messageType_ ;
      /**
       * <pre>
       * type
       * </pre>
       *
       * <code>int32 messageType = 2;</code>
       * @return The messageType.
       */
      @java.lang.Override
      public int getMessageType() {
        return messageType_;
      }
      /**
       * <pre>
       * type
       * </pre>
       *
       * <code>int32 messageType = 2;</code>
       * @param value The messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageType(int value) {
        
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type
       * </pre>
       *
       * <code>int32 messageType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageType() {
        
        messageType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString dataSegment1_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * first data segment
       * </pre>
       *
       * <code>bytes dataSegment1 = 3;</code>
       * @return The dataSegment1.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getDataSegment1() {
        return dataSegment1_;
      }
      /**
       * <pre>
       * first data segment
       * </pre>
       *
       * <code>bytes dataSegment1 = 3;</code>
       * @param value The dataSegment1 to set.
       * @return This builder for chaining.
       */
      public Builder setDataSegment1(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataSegment1_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * first data segment
       * </pre>
       *
       * <code>bytes dataSegment1 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataSegment1() {
        
        dataSegment1_ = getDefaultInstance().getDataSegment1();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString dataSegment2_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * second data segment for expansion in future
       * </pre>
       *
       * <code>bytes dataSegment2 = 4;</code>
       * @return The dataSegment2.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getDataSegment2() {
        return dataSegment2_;
      }
      /**
       * <pre>
       * second data segment for expansion in future
       * </pre>
       *
       * <code>bytes dataSegment2 = 4;</code>
       * @param value The dataSegment2 to set.
       * @return This builder for chaining.
       */
      public Builder setDataSegment2(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataSegment2_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * second data segment for expansion in future
       * </pre>
       *
       * <code>bytes dataSegment2 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataSegment2() {
        
        dataSegment2_ = getDefaultInstance().getDataSegment2();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.tomo.puppet.proto.Packet)
    }

    // @@protoc_insertion_point(class_scope:cn.tomo.puppet.proto.Packet)
    private static final DataPacketProto.Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DataPacketProto.Packet();
    }

    public static DataPacketProto.Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Packet>
        PARSER = new com.google.protobuf.AbstractParser<Packet>() {
      @java.lang.Override
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Packet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public DataPacketProto.Packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_tomo_puppet_proto_Packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_tomo_puppet_proto_Packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020DataPacket.proto\022\024cn.tomo.puppet.proto" +
      "\"\\\n\006Packet\022\021\n\tsessionId\030\001 \001(\005\022\023\n\013message" +
      "Type\030\002 \001(\005\022\024\n\014dataSegment1\030\003 \001(\014\022\024\n\014data" +
      "Segment2\030\004 \001(\014B\023\n\000B\017DataPacketProtob\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_tomo_puppet_proto_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_tomo_puppet_proto_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_tomo_puppet_proto_Packet_descriptor,
        new java.lang.String[] { "SessionId", "MessageType", "DataSegment1", "DataSegment2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
